// SPDX-FileCopyrightText: 2021 - 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef SEARCHPLUGINCONF_H
#define SEARCHPLUGINCONF_H

//插件配置文件conf
#define PLUGININTERFACE_CONF_ROOT "Grand Search"
#define PLUGININTERFACE_CONF_NAME "Name"
#define PLUGININTERFACE_CONF_MODE "Mode"
#define PLUGININTERFACE_CONF_MODE_AUTO "auto"
#define PLUGININTERFACE_CONF_MODE_MANUAL "manual"
#define PLUGININTERFACE_CONF_MODE_TRIGGER "trigger"
#define PLUGININTERFACE_CONF_PRIORITY "Priority"
#define PLUGININTERFACE_CONF_DBUSSERVICE "DBusService"
#define PLUGININTERFACE_CONF_DBUSADDRESS "DBusAddress"
#define PLUGININTERFACE_CONF_DBUSINTERFACE "DBusInterface"
#define PLUGININTERFACE_CONF_INTERFACEVERSION "InterfaceVersion"
#define PLUGININTERFACE_CONF_EXEC "Exec"

#endif // SEARCHPLUGINCONF_H
