// SPDX-FileCopyrightText: 2021 - 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef SEARCHPLUGINPROTOCOL_H
#define SEARCHPLUGINPROTOCOL_H

//protocol v1.0
#define PLUGININTERFACE_PROTOCOL_VERSION "ver"
#define PLUGININTERFACE_PROTOCOL_MISSIONID "mID"
#define PLUGININTERFACE_PROTOCOL_CONTENT "cont"
#define PLUGININTERFACE_PROTOCOL_GROUP "group"
#define PLUGININTERFACE_PROTOCOL_ITEMS "items"
#define PLUGININTERFACE_PROTOCOL_ITEM "item"
#define PLUGININTERFACE_PROTOCOL_NAME "name"
#define PLUGININTERFACE_PROTOCOL_TYPE "type"
#define PLUGININTERFACE_PROTOCOL_ICON "icon"
#define PLUGININTERFACE_PROTOCOL_ACTION "action"

#define PLUGININTERFACE_PROTOCOL_ACTION_OPEN "openitem"

#endif // SEARCHPLUGINPROTOCOL_H
