/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-grand-search/src/dde-grand-search-daemon/searchplugin/interface/abstract/com.deepin.dde.grandsearch.searchplugin.xml -a ./dde-grand-search/toolGenerate/qdbusxml2cpp/com.deepin.dde.grandsearch.searchpluginAdaptor -i ./dde-grand-search/toolGenerate/qdbusxml2cpp/com.deepin.dde.grandsearch.searchplugin.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-grand-search/toolGenerate/qdbusxml2cpp/com.deepin.dde.grandsearch.searchpluginAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SearchPluginAdaptor
 */

SearchPluginAdaptor::SearchPluginAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SearchPluginAdaptor::~SearchPluginAdaptor()
{
    // destructor
}

bool SearchPluginAdaptor::Action(const QString &json)
{
    // handle method call com.deepin.dde.GrandSearch.SearchPlugin.Action
    bool out0;
    QMetaObject::invokeMethod(parent(), "Action", Q_RETURN_ARG(bool, out0), Q_ARG(QString, json));
    return out0;
}

QString SearchPluginAdaptor::Search(const QString &json)
{
    // handle method call com.deepin.dde.GrandSearch.SearchPlugin.Search
    QString out0;
    QMetaObject::invokeMethod(parent(), "Search", Q_RETURN_ARG(QString, out0), Q_ARG(QString, json));
    return out0;
}

bool SearchPluginAdaptor::Stop(const QString &json)
{
    // handle method call com.deepin.dde.GrandSearch.SearchPlugin.Stop
    bool out0;
    QMetaObject::invokeMethod(parent(), "Stop", Q_RETURN_ARG(bool, out0), Q_ARG(QString, json));
    return out0;
}

