/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-grand-search/src/dde-grand-search-daemon/searchplugin/interface/abstract/com.deepin.dde.grandsearch.searchplugin.xml -a ./dde-grand-search/toolGenerate/qdbusxml2cpp/com.deepin.dde.grandsearch.searchpluginAdaptor -i ./dde-grand-search/toolGenerate/qdbusxml2cpp/com.deepin.dde.grandsearch.searchplugin.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DDE_GRANDSEARCH_SEARCHPLUGINADAPTOR_H
#define COM_DEEPIN_DDE_GRANDSEARCH_SEARCHPLUGINADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-grand-search/toolGenerate/qdbusxml2cpp/com.deepin.dde.grandsearch.searchplugin.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.GrandSearch.SearchPlugin
 */
class SearchPluginAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.GrandSearch.SearchPlugin")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.GrandSearch.SearchPlugin\">\n"
"    <method name=\"Search\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"json\"/>\n"
"    </method>\n"
"    <method name=\"Action\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"json\"/>\n"
"    </method>\n"
"    <method name=\"Stop\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"json\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    SearchPluginAdaptor(QObject *parent);
    virtual ~SearchPluginAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool Action(const QString &json);
    QString Search(const QString &json);
    bool Stop(const QString &json);
Q_SIGNALS: // SIGNALS
};

#endif
